### ISSUE TITLE
Hard to find out the "bad" image

### ISSUE THREAD

**Issue by iliakan** [sindresorhus/gulp-imagemin#93]
I tried to convert a bunch of images.

Some of them had problems with gifsicle. It doesn't tell me which one. I had to patch the plugin and find it out the hard way.

Right now I have a problem with an svg. I don't know which one.

Here's a piece of log to see what I mean:

```js
[14:17:24] gulp-imagemin: ✔ 1-js/5-functions-closures/6-memory-management/family-no-father.svg (saved 5 B - 0.1%)
[14:17:24] gulp-imagemin: ✔ 1-js/5-functions-closures/6-memory-management/family.svg (saved 73 B - 2.8%)
[14:17:24] gulp-imagemin: ✔ 1-js/7-js-misc/3-setTimeout-setInterval/setinterval-interval.svg (saved 10 B - 0.5%)
[14:17:24] gulp-imagemin: ✔ 1-js/7-js-misc/3-setTimeout-setInterval/settimeout-interval.svg (saved 16 B - 0.7%)
[14:17:24] gulp-imagemin: ✔ 1-js/8-oop/2-internal-external-interface/coffee-inside.jpg (already optimized)
[14:17:24] gulp-imagemin: ✔ 1-js/8-oop/2-internal-external-interface/coffee.jpg (saved 11.72 kB - 48.3%)
undefined is not a function TypeError: undefined is not a function
    at Object.exports.fn (/js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/plugins/cleanupIDs.js:146:25)
    at /js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:96:27
```

Now I just don't know which svg is actually "broken" (not sure it is, maybe just svgo bug).

**Comment by iliakan** [comment]
I guess, the gulp plugin could pass the files 1-by-1, sequentially, at least in a "debug" mode.
This way the log could help.

**Comment by sindresorhus** [comment]
@kevva Can you try/catch SVGO and any other sync operation inside an async one, so it's always passed to https://github.com/sindresorhus/gulp-imagemin/blob/067e87926cb9d13a7a0717a2f0e2f39b3a9eb310/index.js#L53 ?

**Comment by sindresorhus** [comment]
@iliakan In the meantime you can use [`gulp-debug`](https://github.com/sindresorhus/gulp-debug).

**Comment by iliakan** [comment]
@sindresorhus yeah, using `gulp-debug`, but it doesn't help here, for the same reason why internal logging of `gulp-imagemin` doesn't help.

**Comment by kevva** [comment]
@sindresorhus, shouldn't https://github.com/imagemin/imagemin-svgo/blob/master/index.js#L50 take care of that?

**Comment by sindresorhus** [comment]
You're not wrapping the constructor though. The error might come from that.

**Comment by kevva** [comment]
@iliakan, I've published a new version of imagemin-svgo. Can you update and try again?

**Comment by iliakan** [comment]
@kevva Yeah, I will, in a couple of days (cause I'm refactoring things). 
Unfortunately, svgo breaks my images, so I'm not using it. but that's another issue.

**Comment by kevva** [comment]
Can you share the image so we can test?

**Comment by iliakan** [comment]
@kevva Sorry for the delay, was awaiting for updated svgs from a designer, but it didn't help, now can confirm, the issue persists.

My SVGs:
https://gist.github.com/871eaff6900015231162

My log:
```
/js/javascript-nodejs
> gulp client:minify --root ~/svg --harmony | bunyan
...
[10:11:03] gulp-debug: ../..~/svg/array-pop.svg
[10:11:03] gulp-imagemin: ✔ array-pop.svg (saved 99 B - 3.5%)
[10:11:03] gulp-debug: ../..~/svg/array-shift.svg
[10:11:03] gulp-imagemin: ✔ array-shift.svg (saved 145 B - 3.2%)
[10:11:03] gulp-debug: ../..~/svg/array-speed.svg
[10:11:03] gulp-imagemin: ✔ array-speed.svg (saved 62 B - 1.7%)
[10:11:03] gulp-debug: ../..~/svg/class-inheritance-array-object.svg
undefined is not a function TypeError: undefined is not a function
    at Object.exports.fn (/js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/plugins/cleanupIDs.js:146:25)
    at /js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:96:27
    at Array.forEach (native)
    at full (/js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:94:13)
    at /js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:24:24
    at Array.forEach (native)
    at module.exports (/js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:14:13)
    at /js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:43:21
    at Object.sax.onend (/js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:127:9)
    at emit (/js/javascript-nodejs/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:615:33)
```

My task: 
https://github.com/iliakan/javascript-nodejs/blob/master/tasks/minify.js

**Comment by iliakan** [comment]
P.S.
SVGO cli seems to handle the image, at least the last one:
```
> svgo ~/svg/class-inheritance-array-object.svg
(no errors)
```
